highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: # Required: replace this with your domain
name: Yet Another Blog # Required: will be displayed on every page's header
title: site title # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - Keep Learning, Coding and Building ...
description: "Keep Learning, Coding and Building " # Required

disqus:
  comments: true # Global toggle on/off disqus comment
  shortname: unifreak # Required if you use disqus. Repalce with your disqus shortname here

google_analytics:
  id: "" # Required if you use google analytics. Replace with your tracking id here

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
